WT.WebFlexFramework/WT.WebApplication/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WT.WebApplication.Data.Account;
using WT.WebApplication.Services;

namespace WT.WebApplication.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class AccountController : ControllerBase
    {
        private readonly SignInManager<User> signInManager;
        private readonly UserManager<User> userManager;
        private readonly IEmailService emailService;


        public AccountController(SignInManager<User> signInManager,
                                 UserManager<User> userManager,
                                 IEmailService emailService)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
            this.emailService = emailService;
        }


        public async Task<IActionResult> ExternalLoginCallback()
        {

           var result = await HttpContext.AuthenticateAsync("temp");

            if (!result.Succeeded)
            {
                throw new Exception("external login failed");
            }


            var extUser = result.Principal;

            var sub = extUser?.FindFirst(ClaimTypes.NameIdentifier).Value;

            var issuer = result.Properties.Items["scheme"];


            var emailClaim = result.Principal.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email);
            var userClaim = result.Principal.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name);

            if (emailClaim != null && userClaim != null)
            {
                var user = await userManager.FindByEmailAsync(emailClaim.Value);

                if(user != null)
                {
                    await signInManager.SignInAsync(user, false);
                    await HttpContext.SignOutAsync("temp");
                }
                else
                {
                    // Create the user
                    var newUser = new User
                    {
                        Email = emailClaim.Value,
                        UserName = userClaim.Value.Replace(" ","-"),
                    };

                    var claimDepartment = new Claim("Department", "Guest");
                    var claimPosition = new Claim("Position", "Guest");

                    var newUserResult = await userManager.CreateAsync(newUser, "qazWSX_123");

                    if (result.Succeeded)
                    {
                        await userManager.AddClaimAsync(newUser, claimDepartment);
                        await userManager.AddClaimAsync(newUser, claimPosition);

                        await emailService.SendAsync("Admin@webtech.com",
                            newUser.Email,
                            "You are new In the system",
                            $"If you want to loging with login page use this password: qazWSX_123");

                        await signInManager.SignInAsync(newUser, false);
                        await HttpContext.SignOutAsync("temp");
                    }
                }
               
            }


            return RedirectToPage("/Index");
        }

    }
}

WT.WebFlexFramework/WT.WebApplication/Pages/Account/AccessDenied.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WT.WebApplication.Pages.Account
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WT.WebFlexFramework/WT.WebApplication/Pages/Account/AuthenticatorWithMFASetup.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QRCoder;
using WT.WebApplication.Data.Account;
using WT.WebApplication.ViewModels;

namespace WT.WebApplication.Pages.Account
{
    [Authorize]
    public class AuthenticatorWithMFASetupModel : PageModel
    {
        private readonly UserManager<User> _userManager;

        [BindProperty]
        public SetupMFAViewModel viewModel { get; set; }

        [BindProperty]
        public bool Succeeded { get; set; }

        public AuthenticatorWithMFASetupModel(UserManager<User> userManager)
        {
            _userManager = userManager;
            viewModel = new SetupMFAViewModel();
            Succeeded = false;
        }
        public async Task OnGetAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                await _userManager.ResetAuthenticatorKeyAsync(user);
                var key = await _userManager.GetAuthenticatorKeyAsync(user);
                viewModel.Key = key ?? String.Empty;
                viewModel.QRCodeBytes = GenerateQRCodeBytes(
                   "my web app",
                   this.viewModel.Key,
                   user.Email ?? string.Empty);
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            var user = await _userManager.GetUserAsync(base.User);
            if (user != null && await _userManager.VerifyTwoFactorTokenAsync(
                    user,
                    _userManager.Options.Tokens.AuthenticatorTokenProvider,
                    viewModel.SecurityCode))
            {
                await _userManager.SetTwoFactorEnabledAsync(user, true);
                this.Succeeded = true;
            }
            else
            {
                ModelState.AddModelError("AuthenticatorSetup", "Something went wrong with the authenticator setup.");
            }

            return Page();
        }

        private Byte[] GenerateQRCodeBytes(string provider, string key, string userEmail)
        {
            var qrCodeGenerator = new QRCodeGenerator();
            var qrCodeData = qrCodeGenerator.CreateQrCode(
                $"otpauth://totp/{provider}:{userEmail}?secret={key}&issuer={provider}",
                QRCodeGenerator.ECCLevel.Q);

            var qrCode = new PngByteQRCode(qrCodeData);
            return qrCode.GetGraphic(20);
        }
    }
}

WT.WebFlexFramework/WT.WebApplication/Pages/Account/ConfirmEmail.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WT.WebApplication.Data.Account;

namespace WT.WebApplication.Pages.Account
{
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<User> _userManager;

        [BindProperty]
        public string Message { get; set; } = string.Empty;

        public ConfirmEmailModel(UserManager<User> userManager)
        {
            _userManager = userManager;
        }
        public async Task<IActionResult> OnGet(string userId, string token)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var result = await _userManager.ConfirmEmailAsync(user, token);
                if (result.Succeeded)
                {
                    Message = "Email address is successfully confimred, you can now try to login.";
                    return Page();
                }
            }

            this.Message = "Failed to validate email.";
            return Page();
        }
    }
}

WT.WebFlexFramework/WT.WebApplication/Pages/Account/Login.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using WT.WebApplication.Data.Account;
using WT.WebApplication.Infrastructure.Authorization;
using WT.WebApplication.ViewModels;

namespace WT.WebApplication.Pages.Account
{
    public class LoginModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string ReturnUrl { get; set; }

        [BindProperty]
        public CredentialViewModel Credential { get; set; } = new CredentialViewModel();

        [BindProperty]
        public IEnumerable<AuthenticationScheme> ExternalLoginProviders { get; set; }

        private readonly SignInManager<User> _signInManager;

        public LoginModel(SignInManager<User> signInManager)
        {
            _signInManager = signInManager;
            ReturnUrl = "/";
        }


        public async Task OnGetAsync()
        {
            this.ExternalLoginProviders = await _signInManager.GetExternalAuthenticationSchemesAsync();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            var result = await _signInManager.PasswordSignInAsync(
                this.Credential.Email,
                this.Credential.Password,
                this.Credential.RememberMe,
                false);

            if (result.Succeeded)
            {
                return LocalRedirect(ReturnUrl);
            }
            else
            {
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("/Account/LoginTwoFactorWithAuthenticator",
                        new
                        {
                            RememberMe = Credential.RememberMe
                        });
                }

                if (result.IsLockedOut)
                {
                    ModelState.AddModelError("Login", "You are locked out.");
                }
                else
                {
                    ModelState.AddModelError("Login", "Failed to login.");
                }

                return Page();
            }
        }

        public IActionResult OnPostLoginExternally(string provider)
        {
            var props = new AuthenticationProperties
            {
                RedirectUri = Url.Action("ExternalLoginCallback", "Account"),
                Items =
                {
                    { "uru", ReturnUrl },
                    { "scheme", "Google" }
                }
            };

            return Challenge(props,"Google");
        }
    }
}

WT.WebFlexFramework/WT.WebApplication/Pages/Account/LoginTwoFactor.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WT.WebApplication.Data.Account;
using WT.WebApplication.Services;
using WT.WebApplication.ViewModels;

namespace WT.WebApplication.Pages.Account
{
    public class LoginTwoFactorModel : PageModel
    {
        private readonly UserManager<User> _userManager;
        private readonly IEmailService _emailService;
        private readonly SignInManager<User> _signInManager;

        [BindProperty]
        public EmailMFA EmailMFA { get; set; } = new EmailMFA();

        public LoginTwoFactorModel(UserManager<User> userManager , IEmailService emailService , SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _emailService = emailService;
            _signInManager = signInManager;
        }
        public async Task OnGetAsync(string email , string rememberMe)
        {
            var user = await _userManager.FindByEmailAsync(email);

            var securityCode = await _userManager.GenerateTwoFactorTokenAsync(user, "Email");

            await _emailService.SendAsync("Admin@webtech.com", email, "Web App OPT", $"Please use this code as OTP : {securityCode}");
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            var result = await _signInManager.TwoFactorSignInAsync("Email",
                this.EmailMFA.SecurityCode,
                this.EmailMFA.RememberMe,
                false);

            if (result.Succeeded)
            {
                return RedirectToPage("/Index");
            }
            else
            {
                if (result.IsLockedOut)
                {
                    ModelState.AddModelError("Login2FA", "You are locked out.");
                }
                else
                {
                    ModelState.AddModelError("Login2FA", "Failed to login.");
                }

                return Page();
            }
        }
    }
}

WT.WebFlexFramework/WT.WebApplication/Pages/Account/LoginTwoFactorWithAuthenticator.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WT.WebApplication.Data.Account;
using WT.WebApplication.ViewModels;

namespace WT.WebApplication.Pages.Account
{
    public class LoginTwoFactorWithAuthenticatorModel : PageModel
    {
        private readonly SignInManager<User> signInManager;

        [BindProperty]
        public AuthenticatorMFAViewModel AuthenticatorMFA { get; set; }

        public LoginTwoFactorWithAuthenticatorModel(SignInManager<User> signInManager)
        {
            this.AuthenticatorMFA = new AuthenticatorMFAViewModel();
            this.signInManager = signInManager;
        }

        public void OnGet(bool rememberMe)
        {
            this.AuthenticatorMFA.SecurityCode = string.Empty;
            this.AuthenticatorMFA.RememberMe = rememberMe;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            var result = await signInManager.TwoFactorAuthenticatorSignInAsync(
                this.AuthenticatorMFA.SecurityCode,
                this.AuthenticatorMFA.RememberMe,
                false);

            if (result.Succeeded)
            {
                return RedirectToPage("/Index");
            }
            else
            {
                if (result.IsLockedOut)
                {
                    ModelState.AddModelError("Authenticator2FA", "You are locked out.");
                }
                else
                {
                    ModelState.AddModelError("Authenticator2FA", "Failed to login.");
                }

                return Page();
            }
        }
    }
}

WT.WebFlexFramework/WT.WebApplication/Pages/Account/Logout.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WT.WebApplication.Data.Account;

namespace WT.WebApplication.Pages.Account
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<User> signInManager;

        public LogoutModel(SignInManager<User> signInManager)
        {
            this.signInManager = signInManager;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await signInManager.SignOutAsync();
            return RedirectToPage("/Account/Login");
        }
    }
}

WT.WebFlexFramework/WT.WebApplication/Pages/Account/Register.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using WT.WebApplication.Data.Account;
using WT.WebApplication.Services;
using WT.WebApplication.ViewModels;

namespace WT.WebApplication.Pages.Account
{
    public class RegisterModel : PageModel
    {

        private readonly UserManager<User> _userManager;
        private readonly IEmailService _emailService;

        [BindProperty]
        public RegisterViewModel RegisterViewModel { get; set; } = new RegisterViewModel();

        public RegisterModel(UserManager<User> userManager , IEmailService emailService)
        {
            _userManager = userManager;
            _emailService = emailService;
        }
        
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            // Validate Email Address (optional)

            // Create the user
            var user = new User
            {
                Email = RegisterViewModel.Email,
                UserName = RegisterViewModel.Email,
            };

            var claimDepartment = new Claim("Department", RegisterViewModel.Department);
            var claimPosition = new Claim("Position", RegisterViewModel.Position);

            var result = await _userManager.CreateAsync(user, RegisterViewModel.Password);
            if (result.Succeeded)
            {
                await _userManager.AddClaimAsync(user, claimDepartment);
                await _userManager.AddClaimAsync(user, claimPosition);

                var confirmationToken = await _userManager.GenerateEmailConfirmationTokenAsync(user);

                //////////////////////////////////////////////////////////////
                // To trigger the email confirmation flow, use the code below
                //////////////////////////////////////////////////////////////

                var confirmationLink = Url.PageLink(pageName: "/Account/ConfirmEmail",
                    values: new { userId = user.Id, token = confirmationToken }) ?? "";

                await _emailService.SendAsync("Admin@webtech.com",
                    user.Email,
                    "Please confirm your email",
                    $"Please click on this link to confirm your email address: {confirmationLink}");

                return RedirectToPage("/Account/Login");
            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("Register", error.Description);
                }

                return Page();
            }
        }
    }
}

WT.WebFlexFramework/WT.WebApplication/Pages/Account/AccessDenied.cshtml
@page
@model WT.WebApplication.Pages.Account.AccessDeniedModel
@{
}

<div>
    <h1>Access Denied</h1>
    <br/>
    You don't have access to the page you are looking for.
</div>

WT.WebFlexFramework/WT.WebApplication/Pages/Account/AuthenticatorWithMFASetup.cshtml
@page
@model WT.WebApplication.Pages.Account.AuthenticatorWithMFASetupModel
@{
}
<h3>
 Step 1:  
</h3>
<p>
    please enter the key to your authenticator app:
</p>
<p>
     @if (Model.viewModel.QRCodeBytes != null)
    {
        <img src="@string.Format("data:image/png;base64,{0}",
            Convert.ToBase64String(Model.viewModel.QRCodeBytes))"
                 width="300"
                 height="300" />
    }    
</p>
<br />
<p>
    @Model.viewModel.Key
</p>
<br />
<h3>
    Step 2:
</h3>
<p>
    Please enter the code from your authenticator app:
</p>
<form method="post">   
    @if (Model.Succeeded)
    {
        <div class="alert alert-success">
            The authenticator is successfully setup.
        </div>
    }
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="form-group row">
        <div class="col-2">
            <label asp-for="viewModel.SecurityCode"></label>
        </div>
        <div class="col">
            <input type="text" asp-for="viewModel.SecurityCode" class="form-control" autocomplete="off" />
        </div>
        <span class="text-danger" asp-validation-for="viewModel.SecurityCode"></span>
    </div>
    <div class="form-group row">
        <div class="col-2">
            <input type="submit" class="btn btn-primary" value="Verify" />
        </div>
        <div class="col"> 
            <input type="hidden" asp-for="viewModel.Key" />
        </div>
    </div>
</form>

WT.WebFlexFramework/WT.WebApplication/Pages/Account/ConfirmEmail.cshtml
@page
@model WT.WebApplication.Pages.Account.ConfirmEmailModel
@{
}

<br/>
<p>
    @Model.Message
</p>

WT.WebFlexFramework/WT.WebApplication/Pages/Account/Login.cshtml
@page
@model WT.WebApplication.Pages.Account.LoginModel
@{
}

<div class="container border" style="padding:20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="Credential.Email"></label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="Credential.Email" class="form-control" />
                <span class="text-danger" asp-validation-for="Credential.Email"></span>
            </div>            
        </div>
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="Credential.Password"></label>
            </div>
            <div class="col-5">
                <input type="password" asp-for="Credential.Password" class="form-control" />
                <span class="text-danger" asp-validation-for="Credential.Password"></span>
            </div>            
        </div>
        <div class="mb-3 row form-check">
            <div class="col-2">
                <input type="checkbox" class="form-check-input" asp-for="Credential.RememberMe" />
                <label class="form-check-label" asp-for="Credential.RememberMe"></label>
            </div>
            <div class="col-5">
            </div>
        </div>
        <div class="mb-3 row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Login" />
            </div>
            <div class="col-5">                
            </div>
        </div>
        <br />
        <p>
            Social Media Logins:
            <div class="form-group">
                @foreach(var provider in Model.ExternalLoginProviders)
                {
                    <button type="submit"
                            asp-page-handler="LoginExternally"
                            name="provider"
                            value="@provider.Name"
                            class="btn btn-primary"
                            >
                        Login with @provider.DisplayName
                    </button>
                }
            </div>
        </p>
    </form>
</div>

WT.WebFlexFramework/WT.WebApplication/Pages/Account/LoginTwoFactor.cshtml
@page
@model WT.WebApplication.Pages.Account.LoginTwoFactorModel
@{
}

<p>
    <h3>Please enter the Code from your email:</h3>
</p>
<div class="container border" style="padding:20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="EmailMFA.SecurityCode"></label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="EmailMFA.SecurityCode" class="form-control" />
                <span class="text-danger" asp-validation-for="EmailMFA.SecurityCode"></span>
            </div>
        </div> 
        <div class="mb-3 row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Verify" />
            </div>
            <div class="col-5">
                <input type="hidden" asp-for="EmailMFA.RememberMe" />
            </div>
        </div>
    </form>
</div>

WT.WebFlexFramework/WT.WebApplication/Pages/Account/LoginTwoFactorWithAuthenticator.cshtml
@page
@model WT.WebApplication.Pages.Account.LoginTwoFactorWithAuthenticatorModel
@{
}
<p>
    <h3>Please enter the Code from your authenticator app:</h3>
</p>
<div class="container border" style="padding:20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="AuthenticatorMFA.SecurityCode"></label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="AuthenticatorMFA.SecurityCode" class="form-control" />
                <span class="text-danger" asp-validation-for="AuthenticatorMFA.SecurityCode"></span>
            </div>
        </div> 
        <div class="mb-3 row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Verify" />
            </div>
            <div class="col-5">
                <input type="hidden" asp-for="AuthenticatorMFA.RememberMe" />
            </div>
        </div>
    </form>
</div>

WT.WebFlexFramework/WT.WebApplication/Pages/Account/Logout.cshtml
@page
@model WT.WebApplication.Pages.Account.LogoutModel
@{
}

WT.WebFlexFramework/WT.WebApplication/Pages/Account/Register.cshtml
@page
@model WT.WebApplication.Pages.Account.RegisterModel
@{
}

<h3>User Registration</h3>
<br/>
<div class="container border" style="padding:20px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Email"></label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="RegisterViewModel.Email" class="form-control" />
                <span class="text-danger" asp-validation-for="RegisterViewModel.Email"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Password"></label>
            </div>
            <div class="col-5">
                <input type="password" asp-for="RegisterViewModel.Password" class="form-control" />
                <span class="text-danger" asp-validation-for="RegisterViewModel.Password"></span>
            </div>
        </div>        
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Department"></label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="RegisterViewModel.Department" class="form-control" />
                <span class="text-danger" asp-validation-for="RegisterViewModel.Department"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Position"></label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="RegisterViewModel.Position" class="form-control" />
                <span class="text-danger" asp-validation-for="RegisterViewModel.Position"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Register" />
            </div>
            <div class="col-5">
            </div>
        </div>
    </form>
</div>

WT.WebFlexFramework/WT.WebApplication/Pages/Account/UserProfile.cshtml
@page
@model WT.WebApplication.Pages.Account.UserProfileModel
@{
}

<form method="post">
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="mb-3 row">
        <div class="col-2">
            <label asp-for="UserProfile.Email"></label>
        </div>
        <div class="col-5">
            <input type="text" asp-for="UserProfile.Email" class="form-control" readonly />
            <span class="text-danger" asp-validation-for="UserProfile.Email"></span>
        </div>
    </div>   
    <div class="mb-3 row">
        <div class="col-2">
            <label asp-for="UserProfile.Department"></label>
        </div>
        <div class="col-5">
            <input type="text" asp-for="UserProfile.Department" class="form-control" />
            <span class="text-danger" asp-validation-for="UserProfile.Department"></span>
        </div>
    </div>
    <div class="mb-3 row">
        <div class="col-2">
            <label asp-for="UserProfile.Position"></label>
        </div>
        <div class="col-5">
            <input type="text" asp-for="UserProfile.Position" class="form-control" />
            <span class="text-danger" asp-validation-for="UserProfile.Position"></span>
        </div>
    </div>
    <div class="mb-3 row">
        <div class="col-2">
            <input type="submit" class="btn btn-primary" value="Save" />
        </div>
        <div class="col-5">
        </div>
    </div>
</form>

@if (!string.IsNullOrWhiteSpace(Model.SuccessMessage))
{
    <div class="alert alert-success" role="alert">
        @Model.SuccessMessage
    </div>
}